
export const actionTypes = Object.freeze({
  LOAD_GREEK_UNICODE: Symbol('LOAD_GREEK_UNICODE'),
  LOAD_GREEK_UNICODE_SUCCESS: Symbol('LOAD_GREEK_UNICODE_SUCCESS'),
  LOAD_GREEK_UNICODE_FAILURE: Symbol('LOAD_GREEK_UNICODE_FAILURE'),
});
